### PR TITLE
Reworked logic and tail feature

### PR DESCRIPTION
**Pull request by wallace11**
Sorry for the frequent requests. This time I tried to group as many commits as I could.

1. `os.popen` is apparently [deprecated](https://docs.python.org/2/library/os.html#os.popen) and considered bad practice in general (mostly for security reasons).
I reworked the same functionality using Python commands, and even though not so elegant of a solution as I'd have liked it to be, running timing test showed very good results.
Here's the function I used for timing:
```python
def timing(f):
    def wrap(*args):
        time1 = time.time()
        ret = f(*args)
        time2 = time.time()
        print '%s function took %0.3f ms' % (f.func_name, (time2-time1)*1000.0)
        return ret
    return wrap
```
And the tested functions:
```python
@timing
def list_gpg(top):
    t = []
    for root, dirs, files in walk(top):
        for f in files:
            name, ext = path.splitext(f)
            if ext == ".gpg":
                t += [name if root == top else "{}/{}".format(path.relpath(root, top), name)]
    return sorted(t)

@timing
def list_gpg_find():
    pipe = popen("find ~/.password-store/ | sed '/gpg$/!d;s/.*.password-store\///;s/.gpg$//'")
    output = pipe.read()
    return output.splitlines()
```
I tried writing "amazon" and here's the result:
```
ulauncher-password-store | 2018-05-12 16:51:43,787 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
ulauncher-password-store | 2018-05-12 16:51:46,091 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 0.450 ms
list_gpg_find function took 14.470 ms
ulauncher-password-store | 2018-05-12 16:51:46,107 | DEBUG | ulauncher.api.client.Client: send() | Send message
ulauncher-password-store | 2018-05-12 16:51:55,047 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 1.227 ms
list_gpg_find function took 18.935 ms
ulauncher-password-store | 2018-05-12 16:51:55,069 | DEBUG | ulauncher.api.client.Client: send() | Send message
ulauncher-password-store | 2018-05-12 16:51:55,296 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 1.483 ms
list_gpg_find function took 21.258 ms
ulauncher-password-store | 2018-05-12 16:51:55,320 | DEBUG | ulauncher.api.client.Client: send() | Send message
ulauncher-password-store | 2018-05-12 16:51:55,646 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 2.076 ms
list_gpg_find function took 18.653 ms
ulauncher-password-store | 2018-05-12 16:51:55,668 | DEBUG | ulauncher.api.client.Client: send() | Send message
ulauncher-password-store | 2018-05-12 16:51:56,416 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 1.292 ms
list_gpg_find function took 15.851 ms
ulauncher-password-store | 2018-05-12 16:51:56,434 | DEBUG | ulauncher.api.client.Client: send() | Send message
ulauncher-password-store | 2018-05-12 16:51:56,542 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
list_gpg function took 1.470 ms
list_gpg_find function took 21.830 ms
```
I actually wanted to use the internal `list` command at first, using [subprocess.check_output](https://docs.python.org/2/library/subprocess.html#subprocess.check_output) but the output format is just so annoying to work with that I gave up on this idea.
However, one advantage this method could have is listing passwords that aren't stored at `~/password-store` and are known to `pass`. 
Maybe we should consider adding an option for selecting different directory path? I'm not entirely sure...

2. This one is a bit of a stretch but I wanted to also be able to use the `tail` extension command to show other helpful information (such as login info, etc.) 
I wasn't sure how to implement this at first, but since it's probably going to be rarely used I disabled it by default and allowed it to be triggered via the last query `tail`.
Also, with a long list it can, again, become very nasty (and slow) so I limited it to one result only, since it's probably only going to be used on pin-point searches.
Finally, there's an annoying limitation where an OS password prompt will pop up before we can access the tail information (if outside the timeout zone) and I couldn't find a proper way to re-run the search. Unless you have something in mind, the user will have to recreate his query somehow (delete and retype the "l" in "tail", or something) for the tail information to display.

### CODE REVIEW

**Comment by seqizz** [comment]
Thanks again for the work. Sorry for late response, busy day. I'll try to check & merge tonight :+1:

**Comment by seqizz** [comment]
Hi again,
This looks great. It was bad idea to use find/sed anyway. Few ideas and questions before merge:
- If we can give the option to use another directory, maybe we should. Since pass itself allows this with an environment parameter.
- Problem with `tail` is currently we don't even have the ability to use `pass edit` over ulauncher. I am not sure what are we trying to accomplish here, just copying the non-password stuff won't be helpful too much, you'll still need to paste it somewhere and this is harder than running `pass tail ...` in shell (imho, I am not using this extension since I don't have the use case), but if you think this is helpful, we can merge. It's optional anyway.
- Could you also edit the `README.md`, we won't need sed & find anymore :) I will do this later if you don't have time.

**Comment by wallace11** [comment]
Hi, thanks for the reply

- I'll do 1 and 3, probably tomorrow
- My use case for `tail` is always for finding the user name . Sometimes there are services that force you to use a predefined user name which I tend to save as an extra information. I actually implemented it so that the data will only be displayed (the copy action is still the password). That's not EXTREMELY useful, and as you mentioned, maybe some people will prefer doing this on the terminal anyway, but I think options are always good to have :) However, I'm not sure that my method is the best way to accomplish this `<keyword> <query1> <query2> <...> tail`. The other option is moving the `tail` after the keyword, but I personally find this somewhat clumsy.

**Comment by seqizz** [comment]
I'm using passff, it can find & fill the username value too. This might be why I'm not using pass on shell lately 😁
I'll also somehow try to implement `generate` function when I have time, not sure how yet.
Thanks again & will wait for update 👍

**Comment by wallace11** [comment]
Pushed the changes we discussed on!
And a `generate` function sounds awesome! `pwgen` can be used for that, but maybe it's possible to do entirely in Python... Never tried something like that though.

**Pull request merged**
